spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:29092"
      bindings:
        test:
          group: test-consumer-group
          destination: test
          content-type: application/json
  elasticsearch:
    uris: http://localhost:9200
