spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: test
    password: 1234
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-consumer-group
      auto-offset-reset: latest
    producer:
      bootstrap-servers: localhost:9092

  redis:
    host: localhost
    port: 6379
