spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: test-consumer-group
      auto-offset-reset: latest
    producer:
      bootstrap-servers: localhost:29092
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
  elasticsearch:
    rest:
      uris: http://localhost:9200

